---
name: Main
on: [push, pull_request]
env:
  DOCKER_BUILDKIT: 1
  KUBECONFIG: ./kubeconfig
jobs:
  # This uses the reusable-single-node.yaml template
  single-node:
    name: "Single node with defaults"
    uses: ./.github/workflows/reusable-single-node.yaml

  single-node-custom-ports:
    name: "Single node with custom service ports"
    uses: ./.github/workflows/reusable-single-node.yaml
    with:
      # Defaults to 6443
      kube_apiserver_port: "8080"
      # Defaults to 10250
      kubelet_port: "20250"
      # Defaults to 2379
      etcd_port: "9090"

  # This uses the reusable-multi-node.yaml template
  multi-node:
    name: "Multi node with defaults"
    uses: ./.github/workflows/reusable-multi-node.yaml

  multi-node-custom-ports:
    name: "Multi node with custom service ports"
    uses: ./.github/workflows/reusable-multi-node.yaml
    with:
      # Defaults to 6443
      kube_apiserver_port: "8080"
      # Defaults to 10250
      kubelet_port: "20250"
      # Defaults to 2379
      etcd_port: "9090"

